-- =====================================================================
-- V1 baseline: esquema COMPLETO de servicio-propiedades (BD alquilaya_propiedades).
-- Generado con pg_dump del esquema real (creado por ddl-auto en dev) para que
-- una BD de prod NUEVA + Flyway + ddl-auto=validate arranque sin fallar.
-- Consolidado: reemplaza las migraciones dev-only movidas a ../legacy/.
-- =====================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: configuracion_reserva; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracion_reserva (
    id bigint NOT NULL,
    expiracion_horas integer NOT NULL,
    fecha_actualizacion timestamp(6) without time zone
);


--
-- Name: cuotas_grupo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cuotas_grupo (
    id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    estudiante_id bigint NOT NULL,
    fecha_pago timestamp(6) without time zone,
    grupo_id bigint NOT NULL,
    monto numeric(38,2) NOT NULL,
    payment_id character varying(255),
    reserva_id bigint NOT NULL
);


--
-- Name: cuotas_grupo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cuotas_grupo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuotas_grupo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: denuncias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.denuncias (
    id bigint NOT NULL,
    denunciante_id bigint,
    descripcion text,
    estado character varying(20) NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    motivo character varying(20) NOT NULL,
    propiedad_id bigint NOT NULL,
    CONSTRAINT denuncias_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'REVISADA'::character varying, 'DESCARTADA'::character varying])::text[]))),
    CONSTRAINT denuncias_motivo_check CHECK (((motivo)::text = ANY ((ARRAY['FRAUDE'::character varying, 'INFO_FALSA'::character varying, 'DUPLICADO'::character varying, 'CONTACTO_EXTERNO'::character varying, 'INAPROPIADO'::character varying, 'OTRO'::character varying])::text[])))
);


--
-- Name: denuncias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.denuncias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.denuncias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eventos_propiedad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eventos_propiedad (
    id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    perfil_id bigint,
    propiedad_id bigint NOT NULL,
    tipo character varying(20) NOT NULL,
    CONSTRAINT eventos_propiedad_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['VISTA'::character varying, 'CONTACTO'::character varying])::text[])))
);


--
-- Name: eventos_propiedad_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.eventos_propiedad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_propiedad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favoritos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favoritos (
    id bigint NOT NULL,
    estudiante_id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    propiedad_id bigint NOT NULL
);


--
-- Name: favoritos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favoritos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favoritos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grupos_roommate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grupos_roommate (
    id bigint NOT NULL,
    codigo_invitacion character varying(255) NOT NULL,
    creador_estudiante_id bigint NOT NULL,
    cupos_totales integer NOT NULL,
    descripcion character varying(500),
    estado character varying(255) NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    nombre character varying(255),
    propiedad_id bigint NOT NULL,
    CONSTRAINT grupos_roommate_estado_check CHECK (((estado)::text = ANY ((ARRAY['ABIERTO'::character varying, 'COMPLETO'::character varying, 'RESERVADO'::character varying, 'CERRADO'::character varying])::text[])))
);


--
-- Name: grupos_roommate_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grupos_roommate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupos_roommate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: habitaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.habitaciones (
    id bigint NOT NULL,
    area double precision,
    descripcion text,
    estado character varying(20) NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    nombre character varying(100) NOT NULL,
    orden integer NOT NULL,
    precio numeric(38,2) NOT NULL,
    propiedad_id bigint NOT NULL,
    CONSTRAINT habitaciones_estado_check CHECK (((estado)::text = ANY ((ARRAY['LIBRE'::character varying, 'RESERVADA'::character varying, 'OCUPADA'::character varying, 'MANTENIMIENTO'::character varying])::text[])))
);


--
-- Name: habitaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.habitaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.habitaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: miembros_grupo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.miembros_grupo (
    id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    estudiante_id bigint NOT NULL,
    fecha_union timestamp(6) without time zone,
    grupo_id bigint NOT NULL,
    CONSTRAINT miembros_grupo_estado_check CHECK (((estado)::text = ANY ((ARRAY['CREADOR'::character varying, 'UNIDO'::character varying, 'SOLICITADO'::character varying])::text[])))
);


--
-- Name: miembros_grupo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.miembros_grupo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.miembros_grupo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: outbox_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbox_events (
    id bigint NOT NULL,
    aggregate_id character varying(100) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    attempts integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_id uuid NOT NULL,
    event_type character varying(100) NOT NULL,
    last_error text,
    payload text NOT NULL,
    sent_at timestamp(6) without time zone,
    topic character varying(100) NOT NULL
);


--
-- Name: outbox_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.outbox_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: precio_temporadas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.precio_temporadas (
    id bigint NOT NULL,
    etiqueta character varying(60),
    fecha_fin date NOT NULL,
    fecha_inicio date NOT NULL,
    precio numeric(38,2) NOT NULL,
    propiedad_id bigint NOT NULL
);


--
-- Name: precio_temporadas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.precio_temporadas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.precio_temporadas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: processed_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processed_events (
    consumer_name character varying(100) NOT NULL,
    event_id uuid NOT NULL,
    processed_at timestamp(6) without time zone NOT NULL
);


--
-- Name: propiedad_imagenes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.propiedad_imagenes (
    id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    orden integer,
    url character varying(512) NOT NULL,
    propiedad_id bigint NOT NULL,
    externa boolean NOT NULL
);


--
-- Name: propiedad_imagenes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.propiedad_imagenes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.propiedad_imagenes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: propiedad_reglas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.propiedad_reglas (
    propiedad_id bigint NOT NULL,
    regla character varying(255)
);


--
-- Name: propiedad_servicios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.propiedad_servicios (
    propiedad_id bigint NOT NULL,
    servicio character varying(255)
);


--
-- Name: propiedad_servicios_estado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.propiedad_servicios_estado (
    propiedad_id bigint NOT NULL,
    estado character varying(20),
    servicio character varying(255),
    CONSTRAINT propiedad_servicios_estado_estado_check CHECK (((estado)::text = ANY ((ARRAY['INCLUIDO'::character varying, 'APARTE'::character varying, 'NO_DISPONIBLE'::character varying])::text[])))
);


--
-- Name: propiedades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.propiedades (
    id bigint NOT NULL,
    aprobado_por_admin boolean,
    area double precision,
    arrendador_id bigint NOT NULL,
    calificacion double precision,
    descripcion text,
    direccion character varying(255) NOT NULL,
    disponible_desde date,
    distancia_metros integer,
    esta_disponible boolean,
    estado character varying(255),
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone,
    imagen_url character varying(255),
    latitud double precision,
    longitud double precision,
    nro_piso integer,
    num_resenas integer,
    periodo_alquiler character varying(255),
    precio numeric(38,2) NOT NULL,
    tipo_propiedad character varying(255),
    titulo character varying(150) NOT NULL,
    ubicacion_gps character varying(255),
    version bigint NOT NULL,
    vistas bigint NOT NULL,
    universidad_id bigint,
    zona_id bigint,
    amoblado boolean,
    capacidad_personas integer,
    fecha_cambio_precio timestamp(6) without time zone,
    fecha_publicacion_programada timestamp(6) without time zone,
    gestion_por_habitacion boolean,
    num_banos integer,
    num_dormitorios integer,
    politica_cancelacion character varying(20),
    precio_anterior numeric(38,2),
    tiene_cocina boolean,
    tiene_sala boolean,
    video_url character varying(512),
    fecha_ultima_confirmacion timestamp(6) without time zone,
    requiere_reconfirmacion boolean,
    CONSTRAINT propiedades_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'APROBADO'::character varying, 'RECHAZADO'::character varying])::text[]))),
    CONSTRAINT propiedades_politica_cancelacion_check CHECK (((politica_cancelacion)::text = ANY ((ARRAY['FLEXIBLE'::character varying, 'MODERADA'::character varying, 'ESTRICTA'::character varying])::text[])))
);


--
-- Name: propiedades_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.propiedades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.propiedades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resenas_arrendador; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resenas_arrendador (
    id bigint NOT NULL,
    arrendador_id bigint NOT NULL,
    comentario text,
    estudiante_id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    rating integer NOT NULL,
    visible boolean,
    CONSTRAINT resenas_arrendador_rating_check CHECK (((rating <= 5) AND (rating >= 1)))
);


--
-- Name: resenas_arrendador_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resenas_arrendador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resenas_arrendador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resenas_estudiante; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resenas_estudiante (
    id bigint NOT NULL,
    arrendador_id bigint NOT NULL,
    comentario text,
    estudiante_id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    rating integer NOT NULL,
    visible boolean,
    CONSTRAINT resenas_estudiante_rating_check CHECK (((rating <= 5) AND (rating >= 1)))
);


--
-- Name: resenas_estudiante_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resenas_estudiante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resenas_estudiante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resenas_propiedad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resenas_propiedad (
    id bigint NOT NULL,
    comentario text,
    estudiante_id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    propiedad_id bigint NOT NULL,
    rating integer NOT NULL,
    visible boolean,
    fecha_respuesta timestamp(6) without time zone,
    rating_limpieza integer,
    rating_precio integer,
    rating_trato integer,
    rating_ubicacion integer,
    respuesta_arrendador text,
    CONSTRAINT resenas_propiedad_rating_check CHECK (((rating <= 5) AND (rating >= 1))),
    CONSTRAINT resenas_propiedad_rating_limpieza_check CHECK (((rating_limpieza <= 5) AND (rating_limpieza >= 1))),
    CONSTRAINT resenas_propiedad_rating_precio_check CHECK (((rating_precio <= 5) AND (rating_precio >= 1))),
    CONSTRAINT resenas_propiedad_rating_trato_check CHECK (((rating_trato <= 5) AND (rating_trato >= 1))),
    CONSTRAINT resenas_propiedad_rating_ubicacion_check CHECK (((rating_ubicacion <= 5) AND (rating_ubicacion >= 1)))
);


--
-- Name: resenas_propiedad_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resenas_propiedad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resenas_propiedad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservas (
    id bigint NOT NULL,
    arrendador_id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    estudiante_id bigint NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone,
    fecha_fin date NOT NULL,
    fecha_inicio date NOT NULL,
    monto_total numeric(38,2) NOT NULL,
    motivo_rechazo text,
    propiedad_id bigint NOT NULL,
    recordatorio_pago_enviado boolean,
    version bigint NOT NULL,
    comision numeric(38,2),
    habitacion_id bigint,
    grupo_id bigint,
    motivo_cancelacion text,
    CONSTRAINT reservas_estado_check CHECK (((estado)::text = ANY ((ARRAY['SOLICITADA'::character varying, 'APROBADA'::character varying, 'RECHAZADA'::character varying, 'PAGADA'::character varying, 'FINALIZADA'::character varying, 'CANCELADA'::character varying, 'EXPIRADA'::character varying])::text[])))
);


--
-- Name: reservas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saga_reserva_pago; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saga_reserva_pago (
    saga_id uuid NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    estado_saga character varying(50) NOT NULL,
    intentos integer NOT NULL,
    paso_actual character varying(50) NOT NULL,
    payload text,
    reserva_id bigint NOT NULL,
    ultimo_error text,
    updated_at timestamp(6) without time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT saga_reserva_pago_estado_saga_check CHECK (((estado_saga)::text = ANY ((ARRAY['INICIADA'::character varying, 'ESPERANDO_PAGO'::character varying, 'COMPENSANDO'::character varying, 'COMPLETADA'::character varying, 'FALLIDA'::character varying])::text[]))),
    CONSTRAINT saga_reserva_pago_paso_actual_check CHECK (((paso_actual)::text = ANY ((ARRAY['PAGO_PENDIENTE'::character varying, 'PAGO_CONFIRMADO'::character varying, 'COMPENSACION_REFUND'::character varying, 'COMPENSACION_NOTIFICAR'::character varying, 'FIN'::character varying])::text[])))
);


--
-- Name: configuracion_reserva configuracion_reserva_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion_reserva
    ADD CONSTRAINT configuracion_reserva_pkey PRIMARY KEY (id);


--
-- Name: cuotas_grupo cuotas_grupo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuotas_grupo
    ADD CONSTRAINT cuotas_grupo_pkey PRIMARY KEY (id);


--
-- Name: denuncias denuncias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.denuncias
    ADD CONSTRAINT denuncias_pkey PRIMARY KEY (id);


--
-- Name: eventos_propiedad eventos_propiedad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_propiedad
    ADD CONSTRAINT eventos_propiedad_pkey PRIMARY KEY (id);


--
-- Name: favoritos favoritos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favoritos
    ADD CONSTRAINT favoritos_pkey PRIMARY KEY (id);


--
-- Name: grupos_roommate grupos_roommate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_roommate
    ADD CONSTRAINT grupos_roommate_pkey PRIMARY KEY (id);


--
-- Name: habitaciones habitaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.habitaciones
    ADD CONSTRAINT habitaciones_pkey PRIMARY KEY (id);


--
-- Name: miembros_grupo miembros_grupo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_grupo
    ADD CONSTRAINT miembros_grupo_pkey PRIMARY KEY (id);


--
-- Name: outbox_events outbox_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (id);


--
-- Name: precio_temporadas precio_temporadas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.precio_temporadas
    ADD CONSTRAINT precio_temporadas_pkey PRIMARY KEY (id);


--
-- Name: processed_events processed_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (consumer_name, event_id);


--
-- Name: propiedad_imagenes propiedad_imagenes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.propiedad_imagenes
    ADD CONSTRAINT propiedad_imagenes_pkey PRIMARY KEY (id);


--
-- Name: propiedades propiedades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.propiedades
    ADD CONSTRAINT propiedades_pkey PRIMARY KEY (id);


--
-- Name: resenas_arrendador resenas_arrendador_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resenas_arrendador
    ADD CONSTRAINT resenas_arrendador_pkey PRIMARY KEY (id);


--
-- Name: resenas_estudiante resenas_estudiante_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resenas_estudiante
    ADD CONSTRAINT resenas_estudiante_pkey PRIMARY KEY (id);


--
-- Name: resenas_propiedad resenas_propiedad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resenas_propiedad
    ADD CONSTRAINT resenas_propiedad_pkey PRIMARY KEY (id);


--
-- Name: reservas reservas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT reservas_pkey PRIMARY KEY (id);


--
-- Name: saga_reserva_pago saga_reserva_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saga_reserva_pago
    ADD CONSTRAINT saga_reserva_pago_pkey PRIMARY KEY (saga_id);


--
-- Name: grupos_roommate uk1oqcb5jcgpc9tqebs9akxafrj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_roommate
    ADD CONSTRAINT uk1oqcb5jcgpc9tqebs9akxafrj UNIQUE (codigo_invitacion);


--
-- Name: outbox_events uk7ba1uqwbn85u1g6jg4ja1tk6k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT uk7ba1uqwbn85u1g6jg4ja1tk6k UNIQUE (event_id);


--
-- Name: cuotas_grupo uk_cuota_reserva_est; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuotas_grupo
    ADD CONSTRAINT uk_cuota_reserva_est UNIQUE (reserva_id, estudiante_id);


--
-- Name: favoritos uk_favorito_estudiante_propiedad; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favoritos
    ADD CONSTRAINT uk_favorito_estudiante_propiedad UNIQUE (estudiante_id, propiedad_id);


--
-- Name: miembros_grupo uk_miembro_grupo_est; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_grupo
    ADD CONSTRAINT uk_miembro_grupo_est UNIQUE (grupo_id, estudiante_id);


--
-- Name: resenas_arrendador uk_resena_arr_estudiante_arrendador; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resenas_arrendador
    ADD CONSTRAINT uk_resena_arr_estudiante_arrendador UNIQUE (estudiante_id, arrendador_id);


--
-- Name: resenas_estudiante uk_resena_est_arrendador_estudiante; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resenas_estudiante
    ADD CONSTRAINT uk_resena_est_arrendador_estudiante UNIQUE (arrendador_id, estudiante_id);


--
-- Name: resenas_propiedad uk_resena_prop_estudiante_propiedad; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resenas_propiedad
    ADD CONSTRAINT uk_resena_prop_estudiante_propiedad UNIQUE (estudiante_id, propiedad_id);


--
-- Name: idx_denuncia_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_denuncia_estado ON public.denuncias USING btree (estado);


--
-- Name: idx_denuncia_propiedad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_denuncia_propiedad ON public.denuncias USING btree (propiedad_id);


--
-- Name: idx_evento_prop_tipo_fecha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evento_prop_tipo_fecha ON public.eventos_propiedad USING btree (propiedad_id, tipo, fecha_creacion);


--
-- Name: idx_favorito_estudiante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_favorito_estudiante ON public.favoritos USING btree (estudiante_id);


--
-- Name: idx_precio_temp_propiedad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_precio_temp_propiedad ON public.precio_temporadas USING btree (propiedad_id);


--
-- Name: idx_resena_arr_arrendador; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resena_arr_arrendador ON public.resenas_arrendador USING btree (arrendador_id);


--
-- Name: idx_resena_arr_estudiante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resena_arr_estudiante ON public.resenas_arrendador USING btree (estudiante_id);


--
-- Name: idx_resena_est_arrendador; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resena_est_arrendador ON public.resenas_estudiante USING btree (arrendador_id);


--
-- Name: idx_resena_est_estudiante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resena_est_estudiante ON public.resenas_estudiante USING btree (estudiante_id);


--
-- Name: idx_resena_prop_estudiante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resena_prop_estudiante ON public.resenas_propiedad USING btree (estudiante_id);


--
-- Name: idx_resena_prop_propiedad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resena_prop_propiedad ON public.resenas_propiedad USING btree (propiedad_id);


--
-- Name: idx_reserva_arrendador; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reserva_arrendador ON public.reservas USING btree (arrendador_id);


--
-- Name: idx_reserva_estudiante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reserva_estudiante ON public.reservas USING btree (estudiante_id);


--
-- Name: idx_reserva_propiedad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reserva_propiedad ON public.reservas USING btree (propiedad_id);


--
-- Name: idx_saga_reserva_app; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_saga_reserva_app ON public.saga_reserva_pago USING btree (reserva_id);


--
-- Name: propiedad_reglas fk4natd49kmfk0t6kcoy8cb923b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.propiedad_reglas
    ADD CONSTRAINT fk4natd49kmfk0t6kcoy8cb923b FOREIGN KEY (propiedad_id) REFERENCES public.propiedades(id);


--
-- Name: propiedad_imagenes fkbunkq5te1p5hd70uw1e0jwr1n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.propiedad_imagenes
    ADD CONSTRAINT fkbunkq5te1p5hd70uw1e0jwr1n FOREIGN KEY (propiedad_id) REFERENCES public.propiedades(id) ON DELETE CASCADE;


--
-- Name: propiedad_servicios fkfrn066a5vu26k6vyg8duul22k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.propiedad_servicios
    ADD CONSTRAINT fkfrn066a5vu26k6vyg8duul22k FOREIGN KEY (propiedad_id) REFERENCES public.propiedades(id);


--
-- Name: miembros_grupo fkgly907ovml212q1asavnjns14; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_grupo
    ADD CONSTRAINT fkgly907ovml212q1asavnjns14 FOREIGN KEY (grupo_id) REFERENCES public.grupos_roommate(id);


--
-- Name: propiedad_servicios_estado fkrcvxucgnn2607tu554mc9scbb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.propiedad_servicios_estado
    ADD CONSTRAINT fkrcvxucgnn2607tu554mc9scbb FOREIGN KEY (propiedad_id) REFERENCES public.propiedades(id);


--
-- PostgreSQL database dump complete
--


