-- =====================================================================
-- V3: cronograma de renta mensual recurrente (G2).
--
-- Backbone ADITIVO: una fila por mes de arrendamiento de una reserva activa.
-- NO altera el flujo de pago único existente (reservas.monto_total); esta tabla
-- es solo el CALENDARIO + estado de recordatorios. El cobro real de cada cuota es
-- de servicio-pagos (follow-up); aquí solo se emiten recordatorios vía Outbox.
--
-- Idempotente (IF NOT EXISTS): seguro de re-ejecutar y compatible con el entorno
-- dev donde ddl-auto=update ya pudo crear la tabla desde la entidad JPA.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.cuotas_renta (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id           bigint         NOT NULL,
    numero_cuota         integer        NOT NULL,
    periodo              varchar(7)     NOT NULL,          -- YYYY-MM
    monto                numeric(38,2)  NOT NULL,
    estado               varchar(20)    NOT NULL DEFAULT 'PENDIENTE',
    fecha_vencimiento    date           NOT NULL,
    fecha_pago           date,
    recordatorio_enviado boolean        NOT NULL DEFAULT false,
    fecha_creacion       timestamp(6) without time zone
);

-- Clave natural: evita cuotas duplicadas para el mismo (reserva, mes). Soporta la
-- idempotencia de generarCuotas().
CREATE UNIQUE INDEX IF NOT EXISTS uk_cuota_renta_reserva_num
    ON public.cuotas_renta (reserva_id, numero_cuota);

-- Cronograma por reserva (endpoint de lectura).
CREATE INDEX IF NOT EXISTS idx_cuota_renta_reserva
    ON public.cuotas_renta (reserva_id);

-- Barrido del scheduler: vencidas y "por vencer" filtran por estado + fecha.
CREATE INDEX IF NOT EXISTS idx_cuota_renta_estado_venc
    ON public.cuotas_renta (estado, fecha_vencimiento);
