-- =====================================================================
-- V6: preguntas y respuestas públicas por propiedad (ítem 166).
--
-- Cualquier estudiante puede preguntar algo público sobre una propiedad;
-- el arrendador dueño responde también públicamente (estilo Q&A de
-- marketplaces). FK lógica a propiedades (sin FK física, mismo patrón que
-- el resto del dominio — ver resenas_propiedad).
--
-- Idempotente (IF NOT EXISTS): seguro de re-ejecutar y compatible con el
-- entorno dev donde ddl-auto=update ya pudo crear la tabla desde la entidad JPA.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.preguntas_propiedad (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    propiedad_id       bigint         NOT NULL,
    estudiante_id      bigint         NOT NULL,
    estudiante_nombre  varchar(255)   NOT NULL,
    pregunta           varchar(500)   NOT NULL,
    respuesta          varchar(500),
    fecha_respuesta    timestamp(6) without time zone,
    -- Moderación futura (no se construye UI todavía): solo las visibles
    -- se listan públicamente (ver findByPropiedadIdAndVisibleTrueOrderByFechaCreacionDesc).
    visible            boolean        NOT NULL DEFAULT true,
    fecha_creacion     timestamp(6) without time zone
);

-- Listado público por propiedad, ordenado por recencia (query más común).
CREATE INDEX IF NOT EXISTS idx_pregunta_prop_propiedad
    ON public.preguntas_propiedad (propiedad_id);
