-- ===========================================================================
-- Migración: precios por temporada/ciclo (idea #37)
-- Servicio: servicio-propiedades  (DB: alquilaya_propiedades, PostgreSQL)
-- Contexto: cada propiedad puede definir temporadas [fecha_inicio, fecha_fin] con un
--           precio distinto. La reserva usa el precio de la temporada que cubre su
--           CHECK-IN; si ninguna aplica, el precio base. Solo unidad completa.
--           En dev la tabla la crea ddl-auto; este script la deja para prod.
-- ===========================================================================

\c alquilaya_propiedades

CREATE TABLE IF NOT EXISTS precio_temporadas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    propiedad_id  BIGINT        NOT NULL,
    fecha_inicio  DATE          NOT NULL,
    fecha_fin     DATE          NOT NULL,
    precio        NUMERIC(38,2) NOT NULL,
    etiqueta      VARCHAR(60)
);

CREATE INDEX IF NOT EXISTS idx_precio_temp_propiedad ON precio_temporadas (propiedad_id);
