-- G8-A: bitácora de auditoría append-only de acciones sensibles del ADMIN
-- (cambios de estado de cuenta, edición de usuarios, aprobación/rechazo de KYC,
-- eliminación/anonimización de cuentas). Nunca se actualiza ni se borra.
--
-- Idempotente (CREATE ... IF NOT EXISTS): en dev el esquema lo crea ddl-auto=update
-- a partir de la entidad AuditLog; en prod lo crea esta migración (Flyway + validate).
-- Tipos alineados con la entidad JPA (id IDENTITY, fecha timestamp(6) NOT NULL).

CREATE TABLE IF NOT EXISTS audit_log (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_usuario_id bigint,
    actor_correo     varchar(255),
    accion           varchar(100) NOT NULL,
    entidad          varchar(100) NOT NULL,
    entidad_id       bigint,
    detalle          text,
    ip               varchar(45),
    fecha            timestamp(6) without time zone NOT NULL
);

-- Índices para el listado admin (orden por fecha desc, filtro por actor).
CREATE INDEX IF NOT EXISTS idx_audit_log_fecha ON audit_log (fecha);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor ON audit_log (actor_usuario_id);
