-- #99/#492: suscripciones anónimas a alertas por correo de nuevas propiedades.
--
-- El suscriptor es un visitante del home SIN cuenta: no hay FK a usuarios. Guarda los
-- filtros de interés (zona y/o universidad, tope de precio opcional). Double opt-in:
-- nace `confirmada = false` y solo recibe alertas tras confirmar por correo. Dos tokens
-- aleatorios e impredecibles (SecureRandom, ver SuscripcionAlertaService): uno para
-- confirmar el alta y otro para darse de baja; nunca se exponen ids secuenciales.
--
-- Idempotente (CREATE ... IF NOT EXISTS): en dev el esquema lo crea ddl-auto=update a
-- partir de la entidad SuscripcionAlerta; en prod lo crea esta migración (Flyway + validate).
-- Tipos alineados con la entidad JPA.

CREATE TABLE IF NOT EXISTS suscripciones_alerta (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo              varchar(255) NOT NULL,
    zona_id             bigint,
    universidad_id      bigint,
    precio_max          numeric(12, 2),
    confirmada          boolean NOT NULL DEFAULT false,
    activo              boolean NOT NULL DEFAULT true,
    token_confirmacion  varchar(64) NOT NULL,
    token_baja          varchar(64) NOT NULL,
    fecha_creacion      timestamp(6) without time zone NOT NULL,
    fecha_confirmacion  timestamp(6) without time zone,
    CONSTRAINT uq_suscripcion_alerta_token_confirmacion UNIQUE (token_confirmacion),
    CONSTRAINT uq_suscripcion_alerta_token_baja UNIQUE (token_baja)
);

-- Idempotencia del alta (búsqueda por correo) y matching de propiedades (activo + confirmada).
CREATE INDEX IF NOT EXISTS idx_suscripcion_alerta_correo ON suscripciones_alerta (correo);
CREATE INDEX IF NOT EXISTS idx_suscripcion_alerta_match ON suscripciones_alerta (activo, confirmada);
