-- #99/#492: cola de reintentos para las alertas por correo de nuevas propiedades.
--
-- Robustez de idempotencia en prod. Antes el envío por suscripción era best-effort: si el
-- SMTP fallaba, la alerta se perdía y NO se reintentaba (el evento Kafka ya quedaba marcado
-- como procesado). Ahora el consumidor de propiedades-topic (PropiedadEventListener) encola
-- una fila PENDIENTE por cada suscripción que encaja y EnvioAlertaScheduler la drena con
-- backoff exponencial y reintentos (mismo patrón Transactional Outbox de outbox_events).
--
-- El UNIQUE (propiedad_id, suscripcion_id) da idempotencia GRATIS: un evento reentregado
-- choca con la restricción y se absorbe con ON CONFLICT DO NOTHING (no se duplica el correo).
-- Datos de propiedad y correo DESNORMALIZADOS: el correo debe redactarse aunque la
-- suscripción se dé de baja o la propiedad cambie entre el encolado y el envío.
--
-- Idempotente (CREATE ... IF NOT EXISTS): en dev el esquema lo crea ddl-auto=update a partir
-- de la entidad EnvioAlerta; en prod lo crea esta migración (Flyway + validate). Tipos
-- alineados con la entidad JPA.

CREATE TABLE IF NOT EXISTS envios_alerta (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    propiedad_id     bigint NOT NULL,
    suscripcion_id   bigint NOT NULL,
    correo           varchar(255) NOT NULL,
    titulo           varchar(255),
    precio           numeric(12, 2),
    ubicacion        varchar(255),
    tipo_propiedad   varchar(100),
    token_baja       varchar(64),
    estado           varchar(20) NOT NULL DEFAULT 'PENDIENTE',
    intentos         integer NOT NULL DEFAULT 0,
    proximo_intento  timestamp(6) without time zone NOT NULL,
    ultimo_error     text,
    created_at       timestamp(6) without time zone NOT NULL,
    enviado_at       timestamp(6) without time zone,
    CONSTRAINT uq_envio_alerta_propiedad_suscripcion UNIQUE (propiedad_id, suscripcion_id)
);

-- Índice del drenado del scheduler: filtra estado='PENDIENTE' y ordena por proximo_intento.
CREATE INDEX IF NOT EXISTS idx_envio_alerta_drain ON envios_alerta (estado, proximo_intento);
