-- =====================================================================
-- V1 baseline: esquema COMPLETO de servicio-usuarios (BD postgres).
-- Generado con pg_dump del esquema real (creado por ddl-auto en dev) para que
-- una BD de prod NUEVA + Flyway + ddl-auto=validate arranque sin fallar.
-- Consolidado: reemplaza las migraciones dev-only movidas a ../legacy/.
-- =====================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: arrendadores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.arrendadores (
    id bigint NOT NULL,
    calificacion double precision,
    direccion_propiedades character varying(255),
    es_empresa boolean DEFAULT false,
    latitud double precision,
    longitud double precision,
    nombre_comercial character varying(255),
    ruc character varying(255),
    telefono character varying(255),
    usuario_id bigint NOT NULL,
    num_resenas integer,
    reservas_completadas integer,
    reservas_fallidas integer
);


--
-- Name: arrendadores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.arrendadores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arrendadores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: codigos_email; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.codigos_email (
    id bigint NOT NULL,
    codigo character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    fecha_expiracion timestamp(6) without time zone NOT NULL,
    utilizado boolean NOT NULL
);


--
-- Name: codigos_email_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.codigos_email ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.codigos_email_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuracion_auth; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracion_auth (
    id bigint NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    metodo_verificacion character varying(20) NOT NULL,
    CONSTRAINT configuracion_auth_metodo_verificacion_check CHECK (((metodo_verificacion)::text = ANY ((ARRAY['EMAIL'::character varying, 'WHATSAPP_OTP'::character varying, 'AMBOS'::character varying, 'NINGUNO'::character varying])::text[])))
);


--
-- Name: documentos_verificacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documentos_verificacion (
    id bigint NOT NULL,
    archivo_url character varying(255) NOT NULL,
    comentario_rechazo character varying(255),
    estado_verificacion character varying(255) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone,
    tipo_documento character varying(255) NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT documentos_verificacion_estado_verificacion_check CHECK (((estado_verificacion)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'APROBADO'::character varying, 'RECHAZADO'::character varying])::text[]))),
    CONSTRAINT documentos_verificacion_tipo_documento_check CHECK (((tipo_documento)::text = ANY ((ARRAY['DNI_FRONTAL'::character varying, 'DNI_REVERSO'::character varying, 'CARNE_ESTUDIANTE'::character varying, 'RECIBO_LUZ'::character varying])::text[])))
);


--
-- Name: documentos_verificacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documentos_verificacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_verificacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estudiante_intereses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estudiante_intereses (
    estudiante_id bigint NOT NULL,
    interes character varying(255)
);


--
-- Name: estudiante_zonas_pref; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estudiante_zonas_pref (
    estudiante_id bigint NOT NULL,
    zona character varying(255)
);


--
-- Name: estudiantes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estudiantes (
    id bigint NOT NULL,
    carrera character varying(255),
    ciclo integer,
    codigo_estudiante character varying(255),
    universidad character varying(255),
    verificado boolean NOT NULL,
    usuario_id bigint NOT NULL,
    reservas_completadas integer,
    reservas_fallidas integer,
    bio character varying(600),
    busca_companeros boolean,
    comparte_con character varying(255),
    fecha_mudanza date,
    fuma character varying(255),
    genero character varying(255),
    horario character varying(255),
    instagram character varying(255),
    invitados character varying(255),
    mascotas character varying(255),
    num_companeros integer,
    orden character varying(255),
    presupuesto_max integer,
    presupuesto_min integer,
    ruido character varying(255),
    sociabilidad character varying(255),
    CONSTRAINT estudiantes_ciclo_check CHECK (((ciclo >= 1) AND (ciclo <= 12)))
);


--
-- Name: estudiantes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estudiantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estudiantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funcionalidades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.funcionalidades (
    id bigint NOT NULL,
    categoria character varying(255),
    clave character varying(255) NOT NULL,
    descripcion character varying(255),
    nombre character varying(255) NOT NULL
);


--
-- Name: funcionalidades_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.funcionalidades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funcionalidades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: login_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.login_attempts (
    id bigint NOT NULL,
    correo character varying(120) NOT NULL,
    exito boolean NOT NULL,
    ip character varying(45),
    ts timestamp(6) without time zone NOT NULL
);


--
-- Name: login_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.login_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_verificaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otp_verificaciones (
    id bigint NOT NULL,
    codigo character varying(100) NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    fecha_expiracion timestamp(6) without time zone NOT NULL,
    telefono character varying(255) NOT NULL,
    utilizado boolean NOT NULL
);


--
-- Name: otp_verificaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.otp_verificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_verificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: outbox_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbox_events (
    id bigint NOT NULL,
    aggregate_id character varying(100) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    attempts integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_id uuid NOT NULL,
    event_type character varying(100) NOT NULL,
    last_error text,
    payload text NOT NULL,
    sent_at timestamp(6) without time zone,
    topic character varying(100) NOT NULL
);


--
-- Name: outbox_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.outbox_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permisos (
    id bigint NOT NULL,
    funcionalidad character varying(255) NOT NULL,
    habilitado boolean NOT NULL,
    rol character varying(255) NOT NULL,
    CONSTRAINT permisos_rol_check CHECK (((rol)::text = ANY ((ARRAY['ESTUDIANTE'::character varying, 'ARRENDADOR'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: permisos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permisos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permisos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: processed_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processed_events (
    consumer_name character varying(100) NOT NULL,
    event_id uuid NOT NULL,
    processed_at timestamp(6) without time zone NOT NULL
);


--
-- Name: rol_personalizado_funcionalidades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rol_personalizado_funcionalidades (
    rol_id bigint NOT NULL,
    funcionalidad character varying(255) NOT NULL
);


--
-- Name: roles_personalizados; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles_personalizados (
    id bigint NOT NULL,
    descripcion character varying(255),
    nombre character varying(255) NOT NULL,
    sistema boolean NOT NULL
);


--
-- Name: roles_personalizados_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles_personalizados ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_personalizados_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expiration timestamp(6) without time zone NOT NULL,
    token_hash character varying(64) NOT NULL
);


--
-- Name: token_blacklist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_roles_personalizados; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_roles_personalizados (
    usuario_id bigint NOT NULL,
    rol_personalizado_id bigint NOT NULL
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    apellido character varying(255) NOT NULL,
    correo character varying(255) NOT NULL,
    dni character varying(8) NOT NULL,
    estado character varying(255) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone,
    foto_url character varying(512),
    nombre character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    rol character varying(255) NOT NULL,
    telefono character varying(20),
    telefono_verificado boolean NOT NULL,
    email_verificado boolean DEFAULT false NOT NULL,
    fecha_nacimiento date,
    tipo_login character varying(20) DEFAULT 'LOCAL'::character varying NOT NULL,
    CONSTRAINT usuarios_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'BANNED'::character varying])::text[]))),
    CONSTRAINT usuarios_rol_check CHECK (((rol)::text = ANY ((ARRAY['ESTUDIANTE'::character varying, 'ARRENDADOR'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT usuarios_tipo_login_check CHECK (((tipo_login)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[])))
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arrendadores arrendadores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.arrendadores
    ADD CONSTRAINT arrendadores_pkey PRIMARY KEY (id);


--
-- Name: codigos_email codigos_email_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.codigos_email
    ADD CONSTRAINT codigos_email_pkey PRIMARY KEY (id);


--
-- Name: configuracion_auth configuracion_auth_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion_auth
    ADD CONSTRAINT configuracion_auth_pkey PRIMARY KEY (id);


--
-- Name: documentos_verificacion documentos_verificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_verificacion
    ADD CONSTRAINT documentos_verificacion_pkey PRIMARY KEY (id);


--
-- Name: estudiantes estudiantes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estudiantes
    ADD CONSTRAINT estudiantes_pkey PRIMARY KEY (id);


--
-- Name: funcionalidades funcionalidades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funcionalidades
    ADD CONSTRAINT funcionalidades_pkey PRIMARY KEY (id);


--
-- Name: login_attempts login_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.login_attempts
    ADD CONSTRAINT login_attempts_pkey PRIMARY KEY (id);


--
-- Name: otp_verificaciones otp_verificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_verificaciones
    ADD CONSTRAINT otp_verificaciones_pkey PRIMARY KEY (id);


--
-- Name: outbox_events outbox_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (id);


--
-- Name: permisos permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_pkey PRIMARY KEY (id);


--
-- Name: processed_events processed_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (consumer_name, event_id);


--
-- Name: rol_personalizado_funcionalidades rol_personalizado_funcionalidades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol_personalizado_funcionalidades
    ADD CONSTRAINT rol_personalizado_funcionalidades_pkey PRIMARY KEY (rol_id, funcionalidad);


--
-- Name: roles_personalizados roles_personalizados_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_personalizados
    ADD CONSTRAINT roles_personalizados_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist token_blacklist_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist
    ADD CONSTRAINT token_blacklist_pkey PRIMARY KEY (id);


--
-- Name: outbox_events uk7ba1uqwbn85u1g6jg4ja1tk6k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT uk7ba1uqwbn85u1g6jg4ja1tk6k UNIQUE (event_id);


--
-- Name: token_blacklist uk85fjfavynxyo748kpsj9o6if1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist
    ADD CONSTRAINT uk85fjfavynxyo748kpsj9o6if1 UNIQUE (token_hash);


--
-- Name: permisos uk_permiso_rol_funcionalidad; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT uk_permiso_rol_funcionalidad UNIQUE (rol, funcionalidad);


--
-- Name: roles_personalizados uk_rol_personalizado_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_personalizados
    ADD CONSTRAINT uk_rol_personalizado_nombre UNIQUE (nombre);


--
-- Name: usuarios ukcdmw5hxlfj78uf4997i3qyyw5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukcdmw5hxlfj78uf4997i3qyyw5 UNIQUE (correo);


--
-- Name: estudiantes ukfje3n18j10lxwrl73c0tjg6gx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estudiantes
    ADD CONSTRAINT ukfje3n18j10lxwrl73c0tjg6gx UNIQUE (usuario_id);


--
-- Name: arrendadores ukiirphv7qfg7obcuh7pnxwm3ul; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.arrendadores
    ADD CONSTRAINT ukiirphv7qfg7obcuh7pnxwm3ul UNIQUE (usuario_id);


--
-- Name: funcionalidades ukpngj0dbq5es0gm45qnlbvhr04; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funcionalidades
    ADD CONSTRAINT ukpngj0dbq5es0gm45qnlbvhr04 UNIQUE (clave);


--
-- Name: usuario_roles_personalizados usuario_roles_personalizados_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles_personalizados
    ADD CONSTRAINT usuario_roles_personalizados_pkey PRIMARY KEY (usuario_id, rol_personalizado_id);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: idx_codigo_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_codigo_email ON public.codigos_email USING btree (email);


--
-- Name: idx_login_attempt_correo_exito; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_attempt_correo_exito ON public.login_attempts USING btree (correo, exito);


--
-- Name: idx_login_attempt_correo_ts; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_attempt_correo_ts ON public.login_attempts USING btree (correo, ts DESC);


--
-- Name: ux_usuarios_telefono; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_usuarios_telefono ON public.usuarios USING btree (telefono) WHERE (telefono IS NOT NULL);


--
-- Name: documentos_verificacion fkal022o0vme5m2udabtw4smuxk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_verificacion
    ADD CONSTRAINT fkal022o0vme5m2udabtw4smuxk FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: estudiante_intereses fkgymcnkf2k23krhpdrlk8oxfbb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estudiante_intereses
    ADD CONSTRAINT fkgymcnkf2k23krhpdrlk8oxfbb FOREIGN KEY (estudiante_id) REFERENCES public.estudiantes(id);


--
-- Name: estudiantes fkiqye1ytd68ta1pibrpbtav3bc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estudiantes
    ADD CONSTRAINT fkiqye1ytd68ta1pibrpbtav3bc FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: arrendadores fkkc3dxr1wa360pms1jc7uib69o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.arrendadores
    ADD CONSTRAINT fkkc3dxr1wa360pms1jc7uib69o FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: usuario_roles_personalizados fkmd3realm12b1ec2b4e2erycwa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles_personalizados
    ADD CONSTRAINT fkmd3realm12b1ec2b4e2erycwa FOREIGN KEY (rol_personalizado_id) REFERENCES public.roles_personalizados(id);


--
-- Name: usuario_roles_personalizados fkmd7n3hfllkg9ljfos4fu82hqd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles_personalizados
    ADD CONSTRAINT fkmd7n3hfllkg9ljfos4fu82hqd FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: estudiante_zonas_pref fkpqh7sha2te81qxiqmg11gvdj1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estudiante_zonas_pref
    ADD CONSTRAINT fkpqh7sha2te81qxiqmg11gvdj1 FOREIGN KEY (estudiante_id) REFERENCES public.estudiantes(id);


--
-- Name: rol_personalizado_funcionalidades fkpwhtme5jndrnvxqv8oyqdjiqk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol_personalizado_funcionalidades
    ADD CONSTRAINT fkpwhtme5jndrnvxqv8oyqdjiqk FOREIGN KEY (rol_id) REFERENCES public.roles_personalizados(id);


--
-- PostgreSQL database dump complete
--


