-- Ítem 385: marca clusters de cuentas duplicadas (#8) como "revisados — no es duplicado"
-- para excluirlos de DeteccionDuplicadosService#detectar. El cluster se identifica por
-- (criterio, valor) -- no hay id estable en `usuarios`. NO implica fusión de cuentas
-- (fase 2, fuera de alcance).
--
-- Idempotente (CREATE ... IF NOT EXISTS): en dev el esquema lo crea ddl-auto=update
-- a partir de la entidad DuplicadoRevisado; en prod lo crea esta migración (Flyway + validate).

CREATE TABLE IF NOT EXISTS duplicado_revisado (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterio      varchar(20)  NOT NULL,
    valor         varchar(255) NOT NULL,
    revisado_por  bigint,
    fecha         timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_duplicado_revisado_criterio_valor UNIQUE (criterio, valor)
);
