-- ===========================================================================
-- Migración: distribución de propiedad + gestión por habitaciones
-- Servicio: servicio-propiedades  (DB: alquilaya_propiedades, PostgreSQL)
-- Contexto: features de "capacidad/distribución" y "alquiler por habitaciones".
--           En dev las columnas/tabla las crea ddl-auto; este script las deja
--           explícitas para prod. Todo con IF NOT EXISTS → idempotente y seguro
--           aunque ddl-auto ya las haya creado.
-- ===========================================================================


-- ── Distribución del inmueble (feature capacidad) ──
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS num_dormitorios    INTEGER;
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS num_banos          INTEGER;
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS capacidad_personas INTEGER;
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS tiene_sala         BOOLEAN;
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS tiene_cocina       BOOLEAN;
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS amoblado           BOOLEAN;

-- ── Zona/universidad resueltas al publicar (feature zonas) ──
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS zona_id        BIGINT;
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS universidad_id BIGINT;

-- ── Gestión por habitaciones ──
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS gestion_por_habitacion BOOLEAN NOT NULL DEFAULT FALSE;

-- ── Publicación programada (borradores) ──
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS fecha_publicacion_programada TIMESTAMP;
ALTER TABLE reservas    ADD COLUMN IF NOT EXISTS habitacion_id BIGINT;

-- ── Comisión snapshot de la reserva (feature comisión por zona) ──
ALTER TABLE reservas    ADD COLUMN IF NOT EXISTS comision NUMERIC(12,2);

-- ── Tabla de habitaciones (inmuebles gestionados por habitación) ──
CREATE TABLE IF NOT EXISTS habitaciones (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    propiedad_id    BIGINT       NOT NULL,
    nombre          VARCHAR(100) NOT NULL,
    precio          NUMERIC(12,2) NOT NULL,
    estado          VARCHAR(20)  NOT NULL DEFAULT 'LIBRE',
    area            DOUBLE PRECISION,
    descripcion     TEXT,
    orden           INTEGER      NOT NULL DEFAULT 0,
    fecha_creacion  TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_habitaciones_propiedad ON habitaciones (propiedad_id);
CREATE INDEX IF NOT EXISTS idx_reservas_habitacion    ON reservas (habitacion_id);
