-- =====================================================================
-- V1 baseline: esquema COMPLETO de servicio-pagos (BD alquilaya_pagos).
-- Generado desde el esquema real (ddl-auto en dev) para que una BD de prod
-- NUEVA + Flyway + ddl-auto=validate arranque sin fallar. Consolida y reemplaza
-- las migraciones previas (movidas a ../legacy/) que estaban DESFASADAS del modelo.
-- =====================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: outbox_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbox_events (
    id bigint NOT NULL,
    aggregate_id character varying(100) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    attempts integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_id uuid NOT NULL,
    event_type character varying(100) NOT NULL,
    last_error text,
    payload text NOT NULL,
    sent_at timestamp(6) without time zone,
    topic character varying(100) NOT NULL
);


--
-- Name: outbox_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.outbox_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pagos (
    id bigint NOT NULL,
    estado character varying(255),
    fecha_creacion timestamp(6) without time zone,
    fecha_pago timestamp(6) without time zone,
    monto numeric(38,2),
    payment_id character varying(255),
    preferencia_id character varying(255),
    reserva_id bigint NOT NULL,
    version bigint NOT NULL,
    comision numeric(38,2),
    monto_arrendador numeric(38,2),
    estudiante_id bigint,
    grupo_id bigint
);


--
-- Name: pagos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: outbox_events outbox_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (id);


--
-- Name: pagos pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_pkey PRIMARY KEY (id);


--
-- Name: outbox_events uk7ba1uqwbn85u1g6jg4ja1tk6k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT uk7ba1uqwbn85u1g6jg4ja1tk6k UNIQUE (event_id);


--
-- Name: pagos uk_pago_payment_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT uk_pago_payment_id UNIQUE (payment_id);


--
-- Name: idx_pago_payment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pago_payment ON public.pagos USING btree (payment_id);


--
-- Name: idx_pago_preferencia; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pago_preferencia ON public.pagos USING btree (preferencia_id);


--
-- Name: idx_pago_reserva; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pago_reserva ON public.pagos USING btree (reserva_id);


--
-- PostgreSQL database dump complete
--


