-- =====================================================================
-- V1 baseline: esquema COMPLETO de servicio-mensajeria (BD alquilaya_mensajeria).
-- Generado con pg_dump del esquema real (creado por ddl-auto en dev) para que
-- una BD de prod NUEVA + Flyway + ddl-auto=validate arranque sin fallar.
-- Consolidado: reemplaza las migraciones dev-only movidas a ../legacy/.
-- =====================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: conversaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversaciones (
    id bigint NOT NULL,
    arrendador_id bigint NOT NULL,
    estado character varying(20) NOT NULL,
    estudiante_id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    fecha_ultima_actividad timestamp(6) without time zone NOT NULL,
    propiedad_id bigint NOT NULL,
    ultimo_mensaje_preview character varying(200),
    CONSTRAINT conversaciones_estado_check CHECK (((estado)::text = ANY ((ARRAY['ACTIVA'::character varying, 'SUSPENDIDA'::character varying])::text[])))
);


--
-- Name: conversaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversaciones_ocultas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversaciones_ocultas (
    id bigint NOT NULL,
    conversacion_id bigint NOT NULL,
    fecha_oculta timestamp(6) without time zone NOT NULL,
    perfil_id bigint NOT NULL,
    rol character varying(20) NOT NULL,
    CONSTRAINT conversaciones_ocultas_rol_check CHECK (((rol)::text = ANY ((ARRAY['ESTUDIANTE'::character varying, 'ARRENDADOR'::character varying])::text[])))
);


--
-- Name: conversaciones_ocultas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversaciones_ocultas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversaciones_ocultas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensajes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mensajes (
    id bigint NOT NULL,
    contenido text NOT NULL,
    emisor_perfil_id bigint NOT NULL,
    emisor_rol character varying(20) NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_envio timestamp(6) without time zone NOT NULL,
    fecha_lectura timestamp(6) without time zone,
    conversacion_id bigint NOT NULL,
    CONSTRAINT mensajes_emisor_rol_check CHECK (((emisor_rol)::text = ANY ((ARRAY['ESTUDIANTE'::character varying, 'ARRENDADOR'::character varying])::text[]))),
    CONSTRAINT mensajes_estado_check CHECK (((estado)::text = ANY ((ARRAY['ENVIADO'::character varying, 'LEIDO'::character varying, 'BLOQUEADO'::character varying])::text[])))
);


--
-- Name: mensajes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mensajes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensajes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: moderacion_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.moderacion_log (
    id bigint NOT NULL,
    accion character varying(40) NOT NULL,
    admin_email character varying(150) NOT NULL,
    admin_id bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    motivo character varying(500),
    target_id bigint NOT NULL,
    target_type character varying(20) NOT NULL,
    CONSTRAINT moderacion_log_accion_check CHECK (((accion)::text = ANY ((ARRAY['BLOQUEAR_MENSAJE'::character varying, 'DESBLOQUEAR_MENSAJE'::character varying, 'SUSPENDER_CONVERSACION'::character varying, 'REACTIVAR_CONVERSACION'::character varying])::text[]))),
    CONSTRAINT moderacion_log_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['MENSAJE'::character varying, 'CONVERSACION'::character varying])::text[])))
);


--
-- Name: moderacion_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.moderacion_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.moderacion_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notificaciones (
    id bigint NOT NULL,
    datos jsonb,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    fecha_lectura timestamp(6) without time zone,
    leida boolean NOT NULL,
    mensaje character varying(500) NOT NULL,
    tipo character varying(40) NOT NULL,
    titulo character varying(120) NOT NULL,
    url_destino character varying(255),
    usuario_id bigint NOT NULL,
    CONSTRAINT notificaciones_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['RESERVA_APROBADA'::character varying, 'RESERVA_RECHAZADA'::character varying, 'RESERVA_PAGADA'::character varying, 'RESERVA_CANCELADA'::character varying, 'MENSAJE_NUEVO'::character varying, 'DOCUMENTO_APROBADO'::character varying, 'DOCUMENTO_RECHAZADO'::character varying, 'BIENVENIDA'::character varying, 'RECORDATORIO_PAGO'::character varying, 'ALERTA_ZONA'::character varying, 'SISTEMA'::character varying])::text[])))
);


--
-- Name: notificaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: processed_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processed_events (
    consumer_name character varying(100) NOT NULL,
    event_id uuid NOT NULL,
    processed_at timestamp(6) without time zone NOT NULL
);


--
-- Name: conversaciones_ocultas conversaciones_ocultas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversaciones_ocultas
    ADD CONSTRAINT conversaciones_ocultas_pkey PRIMARY KEY (id);


--
-- Name: conversaciones conversaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversaciones
    ADD CONSTRAINT conversaciones_pkey PRIMARY KEY (id);


--
-- Name: mensajes mensajes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT mensajes_pkey PRIMARY KEY (id);


--
-- Name: moderacion_log moderacion_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.moderacion_log
    ADD CONSTRAINT moderacion_log_pkey PRIMARY KEY (id);


--
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);


--
-- Name: processed_events processed_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (consumer_name, event_id);


--
-- Name: conversaciones_ocultas uk_conv_oculta_par; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversaciones_ocultas
    ADD CONSTRAINT uk_conv_oculta_par UNIQUE (conversacion_id, perfil_id, rol);


--
-- Name: conversaciones uk_conversacion_par_propiedad; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversaciones
    ADD CONSTRAINT uk_conversacion_par_propiedad UNIQUE (estudiante_id, arrendador_id, propiedad_id);


--
-- Name: idx_conv_arrendador_actividad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conv_arrendador_actividad ON public.conversaciones USING btree (arrendador_id, fecha_ultima_actividad DESC);


--
-- Name: idx_conv_estudiante_actividad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conv_estudiante_actividad ON public.conversaciones USING btree (estudiante_id, fecha_ultima_actividad DESC);


--
-- Name: idx_conv_oculta_perfil_rol; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conv_oculta_perfil_rol ON public.conversaciones_ocultas USING btree (perfil_id, rol);


--
-- Name: idx_mod_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mod_target ON public.moderacion_log USING btree (target_type, target_id, fecha DESC);


--
-- Name: idx_msg_conv_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_msg_conv_estado ON public.mensajes USING btree (conversacion_id, estado);


--
-- Name: idx_msg_conv_fecha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_msg_conv_fecha ON public.mensajes USING btree (conversacion_id, fecha_envio);


--
-- Name: idx_notif_usuario_fecha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notif_usuario_fecha ON public.notificaciones USING btree (usuario_id, fecha_creacion DESC);


--
-- Name: idx_notif_usuario_no_leidas; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notif_usuario_no_leidas ON public.notificaciones USING btree (usuario_id, leida);


--
-- Name: mensajes fk8d4yymcmh12qi8j3deratxgtb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT fk8d4yymcmh12qi8j3deratxgtb FOREIGN KEY (conversacion_id) REFERENCES public.conversaciones(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


