-- Ítem 261: reportes de conversación hechos por un participante (acoso, fraude, spam,
-- contenido inapropiado, otro), pendientes de revisión en el panel de moderación admin
-- existente. Tabla nueva y deliberadamente separada de moderacion_log: ese log modela
-- acciones del ADMIN (admin_id/admin_email NOT NULL), no denuncias de usuarios finales.
--
-- Nota ítem 265 ("Tú: …" en el preview del último mensaje): NO requiere cambios de
-- esquema — se resuelve en ConversacionService#toResumen consultando
-- MensajeRepository#findTop1ByConversacionIdOrderByFechaEnvioDesc, sin agregar columna
-- a conversaciones.

CREATE TABLE reportes_conversacion (
    id bigint NOT NULL,
    conversacion_id bigint NOT NULL,
    reportante_id bigint NOT NULL,
    reportante_rol character varying(20) NOT NULL,
    motivo character varying(30) NOT NULL,
    descripcion character varying(500),
    estado character varying(20) NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion timestamp(6) without time zone NOT NULL,
    CONSTRAINT reportes_conversacion_motivo_check
        CHECK (motivo IN ('ACOSO', 'FRAUDE', 'SPAM', 'CONTENIDO_INAPROPIADO', 'OTRO')),
    CONSTRAINT reportes_conversacion_estado_check
        CHECK (estado IN ('PENDIENTE', 'REVISADO', 'DESESTIMADO')),
    CONSTRAINT reportes_conversacion_rol_check
        CHECK (reportante_rol IN ('ESTUDIANTE', 'ARRENDADOR'))
);

ALTER TABLE reportes_conversacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reportes_conversacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY reportes_conversacion
    ADD CONSTRAINT reportes_conversacion_pkey PRIMARY KEY (id);

-- FK física dentro del mismo servicio (mismo estilo que mensajes -> conversaciones en
-- V1): si se borra la conversación, sus reportes se borran con ella.
ALTER TABLE ONLY reportes_conversacion
    ADD CONSTRAINT fk_reporte_conversacion FOREIGN KEY (conversacion_id)
        REFERENCES conversaciones(id) ON DELETE CASCADE;

CREATE INDEX idx_reporte_conversacion ON reportes_conversacion USING btree (conversacion_id);

CREATE INDEX idx_reporte_estado ON reportes_conversacion USING btree (estado);
