spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: servicio-usuarios
            uri: lb://servicio-usuarios
            predicates:
              - Path=/api/v1/usuarios/**, /api/v1/auth/**
            filters:
              - StripPrefix=0
          - id: servicio-propiedades
            uri: lb://servicio-propiedades
            predicates:
              - Path=/api/v1/propiedades/**
            filters:
              - StripPrefix=0
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "http://localhost:*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
