spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: servicio-usuarios
              uri: lb://servicio-usuarios
              predicates:
                - Path=/usuarios/**
              filters:
                - StripPrefix=1
          cors-configurations:
          '[/**]':
            allowed-origin-patterns: "http://localhost:*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
